### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by sobrinho** [pusewicz/refile-cloudinary#4]
Hello,

I'm the current maintainer of refile and its gems and I would like to maintain this project either.

How can I help?

Thanks!

**Comment by pusewicz** [comment]
@sobrinho Thanks a lot for the offer! Please feel free to open PRs and let's see how it goes! ❤️

**Comment by sobrinho** [comment]
@pusewicz @BCecatto is sending some PR through my guidance, I will still review them <3
